name: loja
description: A new Flutter project. Created by Slidy

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_pro: ^1.0.0
  asuka: ^1.0.4
  dartz: ^0.9.1
  string_validator: ^0.1.4
  font_awesome_flutter: ^8.8.1
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  modular_codegen: ^1.0.1+3
  effective_dart: ^1.2.4
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build 
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs
